cloudProject/applications/Account/urls.py
from django.conf.urls import url, patterns
from .views import signin,signup
from django.views.generic import TemplateView

urlpatterns = patterns('cloudProject.applications.Account.views',
      url(r'^signout/$', 'signout', name='vsingout'),
      url(r'^signin/$',signin.as_view(),name='signin'),
      url(r'^signup/$',signup.as_view(),name='signup'),
      url(r'^forbbiden/$','forbidden',name='forbidden'),
)

cloudProject/applications/Home/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('cloudProject.applications.Home.views',
      url(r'^$', 'index', name='init'),
      url(r'^about_us$', 'about_us', name='about_us'),
      url(r'^forbidden$', 'forbidden', name='forbidden'),
)

cloudProject/applications/Video/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('cloudProject.applications.Video.views',
                       url(r'^upload/$', 'upload_video', name='upload_video'),
                       url(r'^show/$', 'get_video', name='get_video'),
)

cloudProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'cloudProject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cloudProject.applications.Home.urls')),
    url(r'^account/', include('cloudProject.applications.Account.urls')),
    url(r'^competitions/', include('cloudProject.applications.Competition.urls')),
]

cloudProject/applications/Client/models.py
from django.db import models

# Create your models here.

cloudProject/applications/Company/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_unicode

class Company(models.Model):
    name = models.CharField(max_length=200)
    nit = models.BigIntegerField()
    description = models.CharField(max_length=255)
    user = models.OneToOneField(User)

    def __unicode__(self):
        title = "%s" % (smart_unicode(self.name))
        return title

cloudProject/applications/Competition/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.encoding import smart_unicode


class Competition(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='ImageCompetitions/%Y/%m/%d')
    startDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    endDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    description = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    active = models.BooleanField()
    # company = models.ForeignKey(Company, null=True)
    company = models.ForeignKey(User)

    def __unicode__(self):
        title = "%s" % (smart_unicode(self.name))
        return title

    def get_competition_url(self):
        # return "http://" + platform.node() + ":8000" + "/competitions/%s/" % (self.id)
        return "/competitions/%s/show/" % (self.id)

    def get_finish_competition_url(self):
        return "/competitions/%s/finish/" % (self.id)

    def get_edit_competition_url(self):
        return "/competitions/%s/edit/" % (self.id)

    def get_upload_video_url(self):
        return "/competitions/%s/upload/" % (self.id)

cloudProject/applications/Home/models.py
from django.db import models

# Create your models here.

cloudProject/applications/Video/models.py
from django.db import models
from django.utils.encoding import smart_unicode
from cloudProject.applications.Competition.models import Competition


class Video(models.Model):
    VIDEO_STATES = (
        ('CON', 'Converted'),
        ('CIP', 'Conversion in process'),
        ('WFC', 'Waiting for conversion'),
    )
    clientfirtsName = models.CharField(max_length=200)
    clientLastName = models.CharField(max_length=200)
    clientEmail = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=255)
    uploadDate = models.DateTimeField(auto_now=False, auto_now_add=True)
    originalVideoPath = models.FileField(upload_to='video')
    convertedVideoPath = models.CharField(max_length=255)
    state = models.CharField(max_length=4, choices=VIDEO_STATES, default='WFC')
    competition = models.ForeignKey(Competition, blank=True, null=True)

    def __unicode__(self):
        title = "%s %s %s" % (self.competition, smart_unicode(self.title), self.clientfirtsName, self.clientLastName)
        return title

cloudProject/applications/Competition/forms.py
import django
from bootstrap3_datetime.widgets import DateTimePicker


class CreateNewCompetition(django.forms.Form):
    name = django.forms.CharField(label='Competition tittle', max_length=100)
    startDate = django.forms.DateTimeField(label='Opening time',
                                           widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm",
                                                                          "pickTime": True}))
    endDate = django.forms.DateField(label='Closing time',
                                     widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm",
                                                                    "pickTime": True}))
    image = django.forms.ImageField(label='Choose Picture')
    description = django.forms.CharField(label='Add description', max_length=200, widget=django.forms.Textarea)

cloudProject/applications/Video/forms.py
import django
from cloudProject.settings import UPLOAD_VIDEO_TYPE


class UploadVideo(django.forms.Form):
    title = django.forms.CharField(label='Video Title', max_length=100)
    clientfirtsName = django.forms.CharField(label='Your First Name')
    clientlastName = django.forms.CharField(label='Your Last Name')
    clientEmail = django.forms.CharField(label='Your email')
    originalVideoPath = django.forms.FileField(label='Choose video')
    description = django.forms.CharField(label='Add a description', max_length=500, widget=django.forms.Textarea)

    def clean(self):
        cleaned_data = self.cleaned_data
        file = cleaned_data.get("originalVideoPath")
        file_exts = ('.ogg', '.3gpp', '.mp4', '.avi', '.flv')

        if file is None:
            raise django.forms.ValidationError('Please select video file first!!')

        if not file.content_type in UPLOAD_VIDEO_TYPE:  # UPLOAD_VIDEO_TYPE contains mime types of required file
            print UPLOAD_VIDEO_TYPE
            print file.content_type
            raise django.forms.ValidationError('Video accepted only in: %s' % ' '.join(file_exts))

        return cleaned_data

cloudProject/applications/Account/views.py
import json

from django.shortcuts import  HttpResponseRedirect,HttpResponse,render_to_response
from django.contrib import auth
from cloudProject.applications.Account.Cookie_utils import set_cookie, get_cookie
from session import Session
from django.contrib.auth.models import User, Group
from django.views.generic import TemplateView
from cloudProject.applications.MongoDB_APP.Company import Company


def signout(request):
    user_id = get_cookie(request,'userId')
    response = HttpResponseRedirect("/")
    Session().do_logout(response,user_id)
    return response


def forbidden(request):

    return render_to_response("Error/forbidden.html")


class signin(TemplateView):

    def post(self,request,*args, **kwargs):
        company = Company()

        username = request.POST.get('username')
        password = request.POST.get('password')

        if company.validate_signin(username,password):
            Session().do_login(username)
            response = HttpResponse(status=200)
            set_cookie(response, 'userId', username)
            return response
        else:
            return HttpResponse(status=401)

class signup(TemplateView):

    def post(self,request,*args, **kwargs):
        diccionario={}

        company = Company()

        username = request.POST.get('username')

        if company.username_exist(username):
            diccionario['msg'] = 'USEREXIST'
            return HttpResponse(json.dumps(diccionario),content_type='application/json')
        else:
            password = request.POST.get('password')
            email = request.POST.get('email')
            companyname = request.POST.get('companyname')
            company.create(username=username,companyName = companyname, email=email, password=password)
            diccionario['msg'] = 'OK'
        return HttpResponse(json.dumps(diccionario),content_type='application/json')

cloudProject/applications/Client/views.py
from django.shortcuts import render

# Create your views here.

cloudProject/applications/Company/views.py
from django.shortcuts import render

# Create your views here.

cloudProject/applications/Competition/views.py
from datetime import datetime

from django.shortcuts import render_to_response, RequestContext, HttpResponseRedirect, render
from django.db.models import Q
from django.utils.timezone import utc
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import TemplateView
from cloudProject.applications.Account.session import Session
from cloudProject.applications.MongoDB_APP.S3Manager import S3Manager


#Import Models
from cloudProject.applications.Account.Cookie_utils import get_cookie
from cloudProject.applications.MongoDB_APP.Company import Company
from cloudProject.applications.MongoDB_APP.Competition import Competition

# Import Forms
from cloudProject.applications.Competition.forms import CreateNewCompetition


def index(request):
    company = get_cookie(request, 'userId')
    user = Session.verify_current_session(company)
    if user['isverify']:
        form = CreateNewCompetition()

        obj_company = Company()
        obj_company.get_competitions(company)
        competitions_list = obj_company.competitions

        paginator = Paginator(competitions_list, 50)

        page = request.GET.get('page')

        try:
            competitions = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            competitions = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            competitions = paginator.page(paginator.num_pages)

        ctx= {'competitions':competitions,'form': form, 'user': user}

        if request.method == 'POST':
            #form = CreateNewCompetition(request.POST, request.FILES)
            #if form.is_valid():
            file_path = S3Manager().upload_memory_media('media/ImageCompetitions/' + datetime.now().strftime("%Y/%m/%d"),
                                                        request.FILES['image'])

            Competition().create(username=company, name=request.POST['name'],
                                      image=file_path,
                                      description=request.POST['description'],
                                      startDate=request.POST.get('startDate'),
                                      endDate=request.POST.get('endDate'),
                                      url='url',
                                      active="true")

            ctx['resp'] = 'OK'

            return HttpResponseRedirect("/competitions")
            #else:
             #   ctx['resp'] = 'BAD'
              #  print form.is_valid
        return render_to_response('Competition/index.html', ctx, context_instance=RequestContext(request))
    else:
        print "entro a forbidden"
        return render_to_response("Error/forbidden.html")

class finish(TemplateView):
    def post(self, request, id_competition):
        Competition().finish(id_competition)

        return HttpResponseRedirect("/competitions")

class edit(TemplateView):
    def post(self, request, id_competition):
        Competition().update(id=id_competition,
                                 name=request.POST['nameedit'],
                                 description = request.POST['descriptionedit'] )

        return HttpResponseRedirect("/competitions")

def show_all_competitions(request):
    list_competitions = Competition().get_all()
    return render(request, 'Competition/active_competitions.html', {'competitions': list_competitions})

cloudProject/applications/Home/views.py
from django.shortcuts import render_to_response, RequestContext

# Create your views here
from cloudProject.applications.Account.Cookie_utils import get_cookie
from cloudProject.applications.Account.session import Session


def index(request):
    user = Session.verify_current_session(get_cookie(request, 'userId'))
    return render_to_response('Home/index.html', {'user': user}, context_instance=RequestContext(request))


def forbidden(request):
    return render_to_response('Home/index.html', context_instance=RequestContext(request))


def about_us(request):
    user = Session.verify_current_session(get_cookie(request, 'userId'))
    return render_to_response('Home/about_us.html', {'user': user}, context_instance=RequestContext(request))

cloudProject/applications/Video/views.py
from django.shortcuts import render, render_to_response
from cloudProject.applications.Video.forms import UploadVideo
from cloudProject.applications.MongoDB_APP.Competition import Competition
from cloudProject.applications.MongoDB_APP.Video import Video
from cloudProject.applications.MongoDB_APP.S3Manager import S3Manager
from cloudProject.applications.Account.Cookie_utils import get_cookie
from cloudProject.applications.Account.session import Session
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from datetime import datetime

def upload_video(request, id_competition):
    competition = Competition()
    competition.get(id_competition)
    if request.method == 'POST':
        form = UploadVideo(request.POST, request.FILES)
        if form.is_valid():
            file_path = S3Manager().upload_memory_media('media/Video/' + datetime.now().strftime("%Y/%m/%d"),
                                                        request.FILES['originalVideoPath'])
            Video().create(id_competition=id_competition,
                              title=request.POST['title'],
                              originalVideoPath=file_path,
                              clientfirtsName=request.POST['clientfirtsName'],
                              clientLastName=request.POST['clientlastName'],
                              description=request.POST['description'],
                              clientEmail=request.POST['clientEmail'])
            return render(request, 'Video/confirmation.html', {'competition': competition})
    else:
        form = UploadVideo()
    return render(request, 'Video/index.html', {'form': form, 'competition': competition})

def confirmation_video(request):
    return render_to_response('Video/confirmation.html')

def get_video(request, id_competition):
    list_video = []
    competition = Competition()
    competition.get(id_competition)
    company = get_cookie(request, 'userId')
    user = Session.verify_current_session(company)

    if user['isverify']:
        print "video logged"
        competition.get_videos(id_competition, "ANY")
        list_video = competition.videos
    else:
        print "video no logge"
        competition.get_videos(id_competition, "CON")
        list_video = competition.videos

    print "list_video"
    print list_video

    videos_per_page = 50
    paginator = Paginator(list_video, videos_per_page)
    page = request.GET.get('page')

    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)

    if user['isverify']:
        return render(request, 'Competition/list_admin_videos.html',
                      {'videos': videos, 'competition': competition, 'user' : user})
    else:
        return render(request, 'Competition/list_public_videos.html',
                      {'videos': videos, 'competition': competition})

cloudProject/templates/Competition/active_competitions.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Active competitions in Sm@rtools</div>
  <!-- Table -->
  <table class="table">
      <thead>
           <tr>
               <th>Name</th>
               <th>Description</th>
               <th>Actions</th>
           </tr>
     </thead>
      <tbody>
   {% for competition in competitions %}
      <tr>
          <td>{{competition.name}}</td>
          <td>{{competition.description}}</td>
          <td>
              <a class="btn btn-success" href="{{competition.get_competition_url}}"><span class="glyphicon glyphicon-share-alt" aria-hidden="true">   </span>  Go to Competition</a>
          </td>
      </tr>
   {% endfor%}
      </tbody>


  </table>
</div>
{% endblock %}

cloudProject/templates/Competition/editcompetitionmodal.html
{% load bootstrap %}
<div id="editcompetition{{forloop.counter}}" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form role="form" onsubmit="return editform(this)"   enctype="multipart/form-data" method="post" action="{{ competition.get_edit_competition_url }}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Edit competition</h4>
                </div>

                <div class="modal-body">
                    <div class="form-group has-feedback">
                            <label class="control-label">Name</label>
                            <input type="text" class="form-control"  name="nameedit" placeholder="name" value="{{ competition.name }}" required />
                            <i class="glyphicon glyphicon-asterisk form-control-feedback"></i>
                            <div class="help-block with-errors"></div>
                        </div>
                    <div class="form-group has-feedback">
                            <label class="control-label">Description</label>
                            <input type="text" class="form-control"  name="descriptionedit" placeholder="description" value="{{ competition.description }}" required />
                            <i class="glyphicon glyphicon-asterisk form-control-feedback"></i>
                            <div class="help-block with-errors"></div>
                        </div>
                    {% csrf_token %}
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <input id="editcompetition" type="submit" class="btn btn-info" value="Save">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
function editform(f) {
if (f.nameedit.value   == '') { alert ('Tittle field is empty');
f.name.focus(); return false; }

if (f.descriptionedit.value  == '') { alert ('Opening date file is empty');
f.startDate.focus(); return false; }

return true; }

</script>

cloudProject/templates/Competition/index.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/content.css' %}">

<div class="GralCont">
    <div class="GCIn">


        <!-- Contenido -->
        <div class="Contenido">

            <div class="MarkerSec">Your active competitions</div>
            <div class="SpV10"></div>


            <div class="HorznX100">
                {% if resp == 'BAD' %}

                {% endif %}
                {% if competitions|length < 1 %}
                <div align="center">
                    <button type="button" data-toggle="modal" data-target="#myModals" class="btn btn-default"
                            aria-label="Left Align">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true">  Add</span>
                    </button>
                </div>
                {% else %}
                <a href="#" data-toggle="modal" data-target="#myModals">Create new competition</a>

                {% endif %}
                {% for competition in competitions %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        {{ competition.name|upper }}
                    </div>
                    <div class="panel-footer">
                        <div class="SpV01"></div>
                        <div class="HorznX20">
                            <img src="{{ MEDIA_URL }}{{competition.image}}" class="img-rounded" width="150" height="80">
                        </div>

                        <div class="HorznX60">
                            <strong>Description:</strong> {{ competition.description }}</br>
                            <strong>Opening Time:</strong> {{ competition.startDate }}</br>
                            <strong>Closing Time:</strong> {{ competition.endDate }}</br>
                            <strong>Url:</strong> <a href="{{ competition.get_competition_url }}">{{ request.scheme}}://{{request.META.HTTP_HOST }}{{ competition.get_competition_url }}</a><br>
                        </div>
                        <div class="HorznX10">
                            <a href="#" data-toggle="modal" data-target="#editcompetition{{forloop.counter}}"
                               class="btn btn-info" role="button">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true">  Edit</span>
                            </a>
                        </div>
                        <div class="HorznX10">
                            <form name="submitForm" method="POST" action="{{competition.get_finish_competition_url}}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-stop" aria-hidden="true">  Finish</span>
                                </button>

                            </form>
                        </div>
                        <div class="SpV01"></div>

                    </div>
                </div>
                {% include "Competition/editcompetitionmodal.html" %}

                {% endfor %}
                <div align="center">
                    <div class="pagination">
                                <span class="step-links">
                                    {% if competitions.has_previous %}
                                        <a href="?page={{ competitions.previous_page_number }}">previous</a>
                                    {% endif %}

                                    <span class="current">
                                        Page {{ competitions.number }} of {{ competitions.paginator.num_pages }}.
                                    </span>

                                    {% if competitions.has_next %}
                                        <a href="?page={{ competitions.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

{% include "Competition/newcompetitionmodal.html" %}

{% endblock%}

cloudProject/templates/Competition/list_admin_videos.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>
<script src="http://content.jwplatform.com/libraries/RbzKMzDD.js"></script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Competition : {{competition.name}}</h3>
    </div>
    <div class="panel-body">

        {% for video in videos %}
        <div class="col-md-12">
               {% if videos|length < 1%}
                    Nothing to Show
                    {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">{{video.title}} - <i>{{video.clientfirtsName}} {{video.clientLastName}}</i>
                    </h4>
                </div>
                <div class="panel-body">
                    <strong>Client:</strong> {{ video.clientfirtsName }} {{ video.clientLastName }}</br>
                    <strong>Client email: </strong>{{ video.clientEmail }}<br>
                    <strong>Description:</strong> {{ video.description }}</br>
                    <strong>Video status: </strong>{{ video.get_state_display }}<br>
                </div>
                <div class="panel-body">
                    <div class="col-md-6">
                        ORIGINAL VIDEO

                        <div id="originalvideo{{forloop.counter}}">
                            <script type="text/javascript">
                                jwplayer('originalvideo{{forloop.counter}}').setup({
                                    file:"{{ MEDIA_URL }}{{video.originalVideoPath}}"
                                });
                            </script>

                        </div>

                    </div>

                    <div class="col-md-6">
                        {% if video.state == 'CON' %}
                        CONVERTED VIDEO
                        <div id="convertedvideo{{forloop.counter}}">
                            <script type="text/javascript">
                                jwplayer('convertedvideo{{forloop.counter}}').setup({
                                    file:"rtmp://s2j7yqs7egvs36.cloudfront.net:1935/cfx/st/mp4:{{video.convertedVideoPath}}"
                                });
                            </script>

                        </div>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if videos.has_previous %}
            <a href="?page={{ videos.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ videos.number }} of {{ videos.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ videos.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

cloudProject/templates/Competition/list_public_videos.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<script src="http://content.jwplatform.com/libraries/RbzKMzDD.js"></script>

<div class="panel panel-primary">
    <div class="panel-heading">
            <h3 class="panel-title">Competition : <strong>{{competition.name}}</strong></h3>
    </div>
    <div class="panel-body">
        <p align="center"><a class="btn btn-success btn-lg" href="{{competition.get_upload_video_url}}"
                             role="button"><span
                class="glyphicon glyphicon-plus-sign"></span> Add video</a></p>

        {% for video in videos %}
           {% if videos|length < 1%}
                Nothing to Show
           {% endif %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">{{video.title}} - <i>{{video.clientfirtsName}} {{video.clientLastName}}</i>
                    </h4>
                </div>
                <div class="panel-body">
                    <div id="convertedvideo{{forloop.counter}}">
                            <script type="text/javascript">
                                jwplayer('convertedvideo{{forloop.counter}}').setup({
                                    file:"rtmp://s2j7yqs7egvs36.cloudfront.net:1935/cfx/st/mp4:{{video.convertedVideoPath}}"
                                });
                            </script>

                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if videos.has_previous %}
            <a href="?page={{ videos.previous_page_number }}"> Previous</a>
        {% endif %}

        <span class="current">
            Page {{ videos.number }} of {{ videos.paginator.num_pages }}.
        </span>

        {% if videos.has_next %}
            <a href="?page={{ videos.next_page_number }}"> Next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

cloudProject/templates/Competition/list_videos.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block content %}
<link href="//vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="//vjs.zencdn.net/4.12/video.js"></script>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Competition : {{competition.name}}</h3>
    </div>
    <div class="panel-body">
        <p align="center"><a class="btn btn-success btn-lg" href="/{{competition.get_upload_video_url}}"
                             role="button"><span
                class="glyphicon glyphicon-plus-sign"></span> Add video</a></p>
        {% for video in videos %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">{{video.title}} - <i>{{video.clientfirtsName}} {{video.clientLastName}}</i>
                    </h4>
                </div>
                <div class="panel-body">
                    <video id="example_video_1" class="video-js vjs-default-skin"
                           controls preload="auto" width="400" height="264"
                           data-setup='{"example_option":true}'>
                        <source src="{% static video.convertedVideoPath %}" type='video/mp4'/>
                        <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a
                            web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports
                                HTML5 video</a></p>
                    </video>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}